DROP ROLE IF EXISTS typoteka;

DROP DATABASE IF EXISTS typoteka_blog;

CREATE ROLE typoteka WITH
    LOGIN
    NOSUPERUSER
    CREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1
    PASSWORD '';

CREATE DATABASE typoteka_blog
    WITH
    OWNER = typoteka
    TEMPLATE = template0
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    CONNECTION LIMIT = -1;
